export const books = [
  {
    id: "crime-and-punishment",
    title: "Crime and Punishment",
    authorId: "dostoevsky",
    year: 1866,
    category: "Psychological Fiction",
    description: "An existential masterpiece that follows Rodion Raskolnikov, an impoverished former law student in Saint Petersburg who formulates a plan to kill an unscrupulous pawnbroker for her money. Raskolnikov argues that with the pawn-broker's money he can perform good deeds to counterbalance the crime, while ridding the world of a vermin. The novel focuses heavily on his mental anguish and moral dilemmas as he attempts to justify his actions and escape the clutches of guilt.",
    image: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?q=80&w=600",
    rating: 4.8,
    coverBg: "linear-gradient(135deg, #4A121A 0%, #1A0508 100%)",
    textColor: "#FFF2F2"
  },
  {
    id: "brothers-karamazov",
    title: "The Brothers Karamazov",
    authorId: "dostoevsky",
    year: 1880,
    category: "Classic Literature",
    description: "Dostoevsky's final and grandest novel, The Brothers Karamazov is a passionate philosophical novel set in 19th-century Russia, that enters deeply into the ethical debates of God, free will, and morality. It is a spiritual drama of moral struggles concerning faith, doubt, judgment, and reason, set against a modernizing Russia, with a plot which revolves around the subject of patricide.",
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?q=80&w=600",
    rating: 4.9,
    coverBg: "linear-gradient(135deg, #1A2E3B 0%, #0D171E 100%)",
    textColor: "#F0F7FF"
  },
  {
    id: "the-trial",
    title: "The Trial",
    authorId: "kafka",
    year: 1925,
    category: "Existentialism",
    description: "One of Franz Kafka's most famous works, it tells the terrifying and surreal story of Josef K., a respectable bank officer who is suddenly arrested and must defend himself against a charge about which he can obtain no information, before a court whose jurisdiction and locations are completely opaque.",
    image: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?q=80&w=600",
    rating: 4.5,
    coverBg: "linear-gradient(135deg, #2C3E50 0%, #0F172A 100%)",
    textColor: "#E2E8F0"
  },
  {
    id: "1984",
    title: "1984",
    authorId: "orwell",
    year: 1949,
    category: "Dystopian Fiction",
    description: "A chillingly prescient dystopian novel that examines the dangers of totalitarianism, extreme political surveillance, and state-mandated mind control. Set in a grey, despairing future where Big Brother is always watching, Winston Smith attempts to rebel against the party's relentless manipulation of history, truth, and human affection.",
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?q=80&w=600",
    rating: 4.7,
    coverBg: "linear-gradient(135deg, #7F1D1D 0%, #450A0A 100%)",
    textColor: "#FEE2E2"
  },
  {
    id: "animal-farm",
    title: "Animal Farm",
    authorId: "orwell",
    year: 1945,
    category: "Political Satire",
    description: "A brilliant political fable that satirizes the events of the Russian Revolution of 1917 and the subsequent Stalinist era of the Soviet Union. A group of farm animals overthrow their exploitative human master to establish an egalitarian society of their own, only to find themselves gradually subjugated by a new elite class of power-hungry pigs.",
    image: "https://images.unsplash.com/photo-1541963463532-d68292c34b19?q=80&w=600",
    rating: 4.6,
    coverBg: "linear-gradient(135deg, #0F5132 0%, #051B11 100%)",
    textColor: "#D1E7DD"
  },
  {
    id: "mans-search-for-meaning",
    title: "Man's Search for Meaning",
    authorId: "frankl",
    year: 1946,
    category: "Psychology & Memoir",
    description: "Viktor Frankl's profoundly inspiring memoir of surviving Nazi concentration camps. He outlines his theory of 'logotherapy'—the belief that the primary human drive is not pleasure, but the pursuit and discovery of what we find meaningful. Even in the face of absolute suffering, Frankl argues, we retain our ultimate freedom: the freedom to choose our attitude.",
    image: "https://images.unsplash.com/photo-1518373714866-3f1478910eb0?q=80&w=600",
    rating: 4.9,
    coverBg: "linear-gradient(135deg, #3D2B1F 0%, #1F1510 100%)",
    textColor: "#FFF8F2"
  },
  {
    id: "the-stranger",
    title: "The Stranger",
    authorId: "camus",
    year: 1942,
    category: "Existentialism",
    description: "A landmark of modernist literature, The Stranger tells the story of Meursault, an emotionally detached, honest French-Algerian who, after attending his mother's funeral, shoots an Arab man on a blindingly hot beach. Meursault's refusal to lie or conform to society's expected emotional rituals leads to his absolute condemnation by the legal court.",
    image: "https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d?q=80&w=600",
    rating: 4.6,
    coverBg: "linear-gradient(135deg, #B25E00 0%, #592F00 100%)",
    textColor: "#FFF5E6"
  },
  {
    id: "thus-spoke-zarathustra",
    title: "Thus Spoke Zarathustra",
    authorId: "nietzsche",
    year: 1883,
    category: "Philosophy",
    description: "Nietzsche's towering philosophical work, written in the form of a dramatic prose poem. It follows the travels and speeches of Zarathustra, a prophet who descends from his mountain isolation to announce the death of God, the arrival of the Übermensch (Overman), the path of self-mastery, and the doctrine of the Eternal Recurrence.",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=600",
    rating: 4.7,
    coverBg: "linear-gradient(135deg, #422006 0%, #1C0A00 100%)",
    textColor: "#FEF08A"
  },
  {
    id: "cairo-trilogy",
    title: "The Cairo Trilogy",
    authorId: "mahfouz",
    year: 1956,
    category: "Historical Fiction",
    description: "Naguib Mahfouz's magnificent masterpiece, comprising Palace Walk, Palace of Desire, and Sugar Street. The trilogy follows three generations of a traditional middle-class Cairo family led by the tyrannical patriarch Al-Sayyid Ahmad Abd al-Jawad, tracing the massive social, political, and religious shifts in Egypt from World War I to the 1952 revolution.",
    image: "https://images.unsplash.com/photo-1507608869274-d3177c8bb4c7?q=80&w=600",
    rating: 4.8,
    coverBg: "linear-gradient(135deg, #9A3412 0%, #431407 100%)",
    textColor: "#FFEDD5"
  },
  {
    id: "meditations",
    title: "Meditations",
    authorId: "aurelius",
    year: 180,
    category: "Philosophy",
    description: "A series of deeply intimate personal writings by Marcus Aurelius, Roman Emperor from 161 to 180 AD, recording his private thoughts on Stoic philosophy, self-discipline, resilience, and the transient nature of life. Written originally as a source of self-guidance, it stands as one of the ultimate philosophical guidebooks in human history.",
    image: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?q=80&w=600",
    rating: 4.9,
    coverBg: "linear-gradient(135deg, #7C2D12 0%, #431407 100%)",
    textColor: "#FFEDD5"
  },
  {
    id: "pride-and-prejudice",
    title: "Pride and Prejudice",
    authorId: "austen",
    year: 1813,
    category: "Classic Literature",
    description: "Jane Austen's ultimate romantic masterpiece centers on the witty Elizabeth Bennet and the proud Mr. Darcy. It is a brilliant critique of the manners, class systems, marriages, and financial dynamics of Regency-era England, illustrating how first impressions can mislead even the sharpest minds.",
    image: "https://images.unsplash.com/photo-1492052722242-2554d0e99e3a?q=80&w=600",
    rating: 4.8,
    coverBg: "linear-gradient(135deg, #15803D 0%, #064E3B 100%)",
    textColor: "#DCFCE7"
  },
  {
    id: "war-and-peace",
    title: "War and Peace",
    authorId: "tolstoy",
    year: 1869,
    category: "Classic Literature",
    description: "Tolstoy's epic masterpiece charts the history of the French invasion of Russia and the impact of the Napoleonic era on Tsarist society through the interweaving fates of five Russian aristocratic families. Blending philosophy with realistic human narratives, it is widely considered one of the greatest novels ever written.",
    image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?q=80&w=600",
    rating: 4.9,
    coverBg: "linear-gradient(135deg, #1E3A8A 0%, #172554 100%)",
    textColor: "#DBEAFE"
  },
  {
    id: "to-the-lighthouse",
    title: "To the Lighthouse",
    authorId: "woolf",
    year: 1927,
    category: "Modernist Literature",
    description: "Virginia Woolf's landmark modernist novel centers on the Ramsay family and their visits to the Isle of Skye. Rich with stream-of-consciousness introspection and philosophical meditation on time, grief, gender roles, and artistic creation, it remains a pioneering literary masterwork.",
    image: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?q=80&w=600",
    rating: 4.6,
    coverBg: "linear-gradient(135deg, #581C87 0%, #3B0764 100%)",
    textColor: "#F3E8FF"
  },
  {
    id: "the-prophet",
    title: "The Prophet",
    authorId: "gibran",
    year: 1923,
    category: "Philosophy",
    description: "Kahlil Gibran's timeless work contains 26 poetic essays delivered by the prophet Almustafa before boarding his ship home. It offers beautiful, deep reflections on love, marriage, children, giving, work, pain, friendship, and death, spoken with exceptional clarity and mystical simplicity.",
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=600",
    rating: 4.8,
    coverBg: "linear-gradient(135deg, #78350F 0%, #451A03 100%)",
    textColor: "#FEF3C7"
  }
];
